version: '3.4'

services:

  wilpsocialmedia.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
    ports:
      - "5100:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro     
    networks:
      - my-app 
 
networks:
  my-app:
    name: mynetwork
    external: true
